# Generated by Django 3.0.8 on 2020-08-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperTrade', '0002_transaction_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='funds',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='user',
            name='investing',
            field=models.IntegerField(default=0),
        ),
    ]
