# Generated by Django 3.0.8 on 2020-08-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperTrade', '0003_auto_20200813_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(default='buy', max_length=16),
            preserve_default=False,
        ),
    ]
